#%RAML 1.0 Library
types:
  OrderItemDetailLib: 
   properties:
      orderItemId:
        required: false
        displayName: OrderItemID
        type: string
      itemId:
        required: false
        displayName: ItemID
        type: string
      itemCount:
        required: false
        displayName: ItemCount
        type: string